// <auto-generated />
using LocalBusinessApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusinessApi.Migrations
{
    [DbContext(typeof(LocalBusinessApiContext))]
    [Migration("20210122180823_FixRestaurantSpelling")]
    partial class FixRestaurantSpelling
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusinessApi.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("KeyBusiness");

                    b.Property<string>("Name");

                    b.Property<string>("StreetAddress");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            KeyBusiness = "Late night bites",
                            Name = "24hr Kabab",
                            StreetAddress = "151 High St"
                        },
                        new
                        {
                            RestaurantId = 2,
                            KeyBusiness = "Casual drinks & street food",
                            Name = "Maria's Cantina",
                            StreetAddress = "132 High St"
                        },
                        new
                        {
                            RestaurantId = 3,
                            KeyBusiness = "Italian dining",
                            Name = "Pastini Ristorante",
                            StreetAddress = "222 Old Town Ave"
                        },
                        new
                        {
                            RestaurantId = 4,
                            KeyBusiness = "Beer on tap & pub food",
                            Name = "O'Leary's Pub",
                            StreetAddress = "100 High St"
                        },
                        new
                        {
                            RestaurantId = 5,
                            KeyBusiness = "French cuisine",
                            Name = "Pierre's Bon Cuisine",
                            StreetAddress = "1310 Rue St Jean"
                        });
                });

            modelBuilder.Entity("LocalBusinessApi.Models.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("KeyBusiness");

                    b.Property<string>("Name");

                    b.Property<string>("StreetAddress");

                    b.HasKey("ShopId");

                    b.ToTable("Shops");

                    b.HasData(
                        new
                        {
                            ShopId = 1,
                            KeyBusiness = "Record Shop",
                            Name = "Ricc's Records",
                            StreetAddress = "123 Groovy Way"
                        },
                        new
                        {
                            ShopId = 2,
                            KeyBusiness = "Professional Audio",
                            Name = "Aubrey's Amps & LoudSpeakers",
                            StreetAddress = "666 Industry Ave"
                        },
                        new
                        {
                            ShopId = 3,
                            KeyBusiness = "Plant Shop",
                            Name = "Les Fluers",
                            StreetAddress = "1300 Rue St Jean"
                        },
                        new
                        {
                            ShopId = 4,
                            KeyBusiness = "Antiques",
                            Name = "Auntie A's Antiques",
                            StreetAddress = "44 Junk St"
                        },
                        new
                        {
                            ShopId = 5,
                            KeyBusiness = "Convenience Store",
                            Name = "General Store",
                            StreetAddress = "15 Old Town Ave"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
